---
- name: config_db | Installing Python Modules
  pip:
    name: "{{ influxdb_python_modules }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: config_db | Ensuring InfluxDB Is Running And Enabled On Boot
  service:
    name: influxdb
    state: started
    enabled: true
  become: true

- name: config_db | Waiting For InfluxDB
  wait_for:
    port: "{{ influxdb_http['bind_port'] }}"

- name: config_db | Use SSL if we have turned on https in config
  set_fact:
    use_ssl: true
  when: influxdb_http['https_enabled']|bool

- name: config_db | Creating InfluxDB(s)
  influxdb_database:
    hostname: "{{ item['host'] }}"
    database_name: "{{ item['name'] }}"
    state: "{{ item['state'] }}"
    port: "{{ influxdb_http['bind_port'] }}"
    ssl: "{{ use_ssl | default(false) }}"
  become: true
  with_items: "{{ influxdb_databases }}"

- name: config_db | Creating InfluxDB Retention Policies
  influxdb_retention_policy:
    hostname: "{{ item['host'] }}"
    database_name: "{{ item['name'] }}"
    policy_name: "{{ item['retention_policy']['name'] }}"
    duration: "{{ item['retention_policy']['duration'] }}"
    replication: "{{ item['retention_policy']['replication'] }}"
    port: "{{ influxdb_http['bind_port'] }}"
    ssl: "{{ use_ssl | default(false) }}"
  become: true
  with_items: "{{ influxdb_databases }}"
  when: >
    item['retention_policy'] is defined and
    item['retention_policy']['enabled']
