---
- name: config_db | Installing Python Modules
  ansible.builtin.pip:
    name: "{{ influxdb_python_modules }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: config_db | Ensuring InfluxDB Is Running And Enabled On Boot
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: true
  become: true

- name: config_db | Waiting For InfluxDB
  ansible.builtin.wait_for:
    port: "{{ influxdb_http['bind_port'] }}"

- name: config_db | Creating InfluxDB(s)
  community.general.influxdb_database:
    hostname: "{{ item['host'] }}"
    database_name: "{{ item['name'] }}"
    state: "{{ item['state'] }}"
    port: "{{ influxdb_http['bind_port'] }}"
    udp_port: "{{ influxdb_udp['bind_port'] }}"
  become: true
  loop: "{{ influxdb_databases }}"

- name: config_db | Creating InfluxDB Retention Policies
  community.general.influxdb_retention_policy:
    hostname: "{{ item['host'] }}"
    database_name: "{{ item['name'] }}"
    policy_name: "{{ item['retention_policy']['name'] }}"
    duration: "{{ item['retention_policy']['duration'] }}"
    replication: "{{ item['retention_policy']['replication'] }}"
    port: "{{ influxdb_http['bind_port'] }}"
    udp_port: "{{ influxdb_udp['bind_port'] }}"
  become: true
  loop: "{{ influxdb_databases }}"
  when:
    - item['retention_policy'] is defined
    - item['retention_policy']['enabled']|bool
